### ISSUE TITLE
Loop don't work on rtsp stream

### ISSUE THREAD

**Issue by sebiiiii** [Leo-C/kodi.addon.autoplay#1]
Hi,
I try to use your scripts to autoplay rtsp stream in LE (worked in LE  11 nightly on RPI Zero 2W)

if stream is down, I go back to libreelec menu, and if stream is up again, it does not show

How can I fix this ?

Thanks

**Comment by sebiiiii** [comment]
It is not related to your script, I close.

**Comment by Leo-C** [comment]
I've not yet tested my code on RPI Zero 2W, but I'm surprised that you can run LE > 9 on RPI Zero
(RPI Zero 2W is broadly equivalent to RPI 3, and RPI 1-2-3 are not supported from LE 10)

**Comment by sebiiiii** [comment]
Le 10 is not supported yet but le11 is in nightlies
